
# NameError: This exception is raised when a variable or function name is not found in the current scope.

print('hello python',1)
print('hello python',2)
a = 10
b = 30
# print(x)
print('hello python',3)
print('hello python',4)

# NameError: name 'x' is not defined
# hello python 1
# hello python 2



# IndexError: This exception is raised when an index is out of range for a list, tuple, or other sequence types.


l1 = [1,2,3,4,5]
print(l1[5])
# IndexError: list index out of range
